# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Library of high performance immutable and persistent data structures for .NET.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://imms.github.io/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
exclude: [Code/, .git, .idea, node_modules, bower_components, API/Working/]
# Build settings
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
